id: 02D
title: Editing and Simplifying Spatial Data
course: 4543-5993-Spatial-Data
part: Part_02
module: Raw_Spatial_Data
sequence: 4
type: lesson
format: notebook
estimated_time: 60 minutes
prerequisites:
- 02A-When_Coordinates_Arent_Enough
- 02B-Distance_Depends_on_Assumptions
- 02C-Scale_Resolution_and_Detail
learning_objectives:
- Explain why spatial data is always edited
- Describe the effects of simplification
- Identify misleading spatial edits
- Reason about abstraction and intent
key_concepts:
- simplification
- abstraction
- editing
- intent
- detail loss
deliverables:
- Completed notebook.ipynb
due: 2026-03-01 23:59
points: '0'
